events {}

http {
  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /backend/ {
      proxy_pass http://backend:8000/;
      limit_req zone=api_limit burst=20 nodelay;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      client_max_body_size 25M;
    }

  }
}